### Get All Users
GET http://localhost:3000/api/users

### Get Single User
GET http://localhost:3000/api/users/64ae28724b942ba0763ad67b

### Create User
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Karson",
  "lastName": "Kelley",
  "email": "karson@email.com",
  "strength": 10,
  "speed": 10,
  "stamina": 10,
  "rizz": 10,
  "magic": 10,
  "stealth": 10,
  "health": 10,
  "kd": 3.79,
  "ratedBy": 0,
  "rated": 0
}

### Update User
PUT http://localhost:3000/api/users/64c6c6593c06e0a5b06a5309
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Kelley",
  "email": "karson@email.com",
  "strength": 10,
  "speed": 9,
  "stamina": 10,
  "rizz": 10,
  "magic": 10,
  "stealth": 10,
  "health": 10,
  "kd": 3.79,
  "ratedBy": 0,
  "rated": 0
}

### Delete User
DELETE http://localhost:3000/api/users/64c6c6593c06e0a5b06a5309
