### Get Users
GET http://localhost:3000

### Create User
POST http://localhost:3000/user
Content-Type: application/json

{
  "firstName": "Mason",
  "lastName": "Capps",
  "email": "mason@email.com",
  "strength": 10,
  "speed": 10,
  "stamina": 10,
  "rizz": 10,
  "magic": 10,
  "stealth": 10,
  "health": 10,
  "kd": 8.79,
  "ratedBy": 0,
  "rated": 0
}
